require('core.globals')
require('core.augroups')
require('core.settings')

vim.defer_fn(function()
  local maps = require('core.mappings')
  require("core.utils").load_mappings(maps)
end, 0)

require('core.plugins')
require('plugins.statusline')
require('core.colors')

-- plugin configs
require('plugins.plugins-conf')
require('plugins.comment')
require('plugins.which-key')
require('plugins.luasnips')
require('plugins.cmp')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.treesitter')
require('plugins.neogit')
require('plugins.gitsigns')
require('plugins.hlslens')
require('plugins.autopairs')
