require('core.augroups')
require('core.settings')

vim.defer_fn(function()
  require("core.utils").load_mappings()
end, 0)

require('core.plugins')
require('custom.globals')
require('custom.statusline')
require('custom.colors')

-- plugin configs
require('plugins.plugins-conf')
require('plugins.comment')
require('plugins.which-key')
require('plugins.luasnips')
require('plugins.cmp')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.treesitter')
require('plugins.neogit')
require('plugins.gitsigns')
require('plugins.hlslens')
require('plugins.autopairs')
